---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7
  - name: centos-6

suites:
  - name: default
    run_list:
      - recipe[opennms::repositories]
      - recipe[opennms_helm::default]
    attributes:
    verifier:
      inspec_tests:
        - test/integration/default
